<a href="https://colab.research.google.com/github/sajid-shahriar/pytorch-tutorial/blob/main/ltb_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Initializing a tensor

In [1]:
import torch
import numpy as np

In [ ]:
#Directly from data
data = [[1,2], [2,3]]
x_data = torch.tensor(data)

In [ ]:
#from numpy array
np_array = np.array(data)
x_data = torch.from_numpy(np_array)

In [ ]:
#from another tensor
x_ones = torch.ones_like(x_data) #retains the properties of x_data
print(f"Ones Tensor: \n {x_ones}\n")

x_random = torch.rand_like(x_data, dtype=torch.float) #overrides the datatype of x_data
print(f"random tensor: \n {x_random}\n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

random tensor: 
 tensor([[0.2019, 0.4215],
        [0.3189, 0.6291]])



In [ ]:
#with random or constant values

shape = (2, 3) #tuple of tensor dimensions, used to specify the dimension of tensors

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n{rand_tensor}\n")
print(f"Ones tensor: \n{ones_tensor}\n")
print(f"Zeroes tensor: \n{zeros_tensor}\n")

Random tensor: 
tensor([[0.0888, 0.3069, 0.9308],
        [0.0867, 0.2753, 0.8145]])

Ones tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeroes tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



#Attributes of a tensor

In [ ]:
# Tensor attributes describe
# their shape, datatype, and the device on which they are stored.

tensor = torch.rand(3,4)
print(f"tensor: \n{tensor}\n")

#attribute
print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device of the tensor: {tensor.device}")

tensor: 
tensor([[0.0717, 0.9305, 0.9172, 0.9197],
        [0.9475, 0.3144, 0.4113, 0.6141],
        [0.3127, 0.4946, 0.7191, 0.6408]])

shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of the tensor: cpu


# Operations on tensor

1200 operations is possible. They can be found at [here.](https://docs.pytorch.org/docs/2.13/torch.html)

In [ ]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

print(f"Device of tensor: {tensor.device}")

Device of tensor: cuda:0


In [ ]:
# Numpy like indexing and slicing

tensor = torch.rand(4,4)

print(f"tensor: \n{tensor}\n")

print(f"First row: \n{tensor[0]}\n")
print(f"First column: \n{tensor[:, 0]}\n")
print(f"Last column: \n{tensor[:, -1]}\n")
print(f"Last column: \n{tensor[..., -1]}\n") #good for greater than 2d tensor



tensor: 
tensor([[0.4130, 0.6300, 0.6954, 0.0936],
        [0.0321, 0.0377, 0.7239, 0.4694],
        [0.6381, 0.6953, 0.6005, 0.9967],
        [0.7694, 0.1750, 0.9768, 0.4009]])

First row: 
tensor([0.4130, 0.6300, 0.6954, 0.0936])

First column: 
tensor([0.4130, 0.0321, 0.6381, 0.7694])

Last column: 
tensor([0.0936, 0.4694, 0.9967, 0.4009])

Last column: 
tensor([0.0936, 0.4694, 0.9967, 0.4009])



In [ ]:
t1 = torch.cat([tensor, tensor], dim = 1)
print(f"t1: \n{t1}\n")

t2 = torch.cat([tensor, tensor], dim = 0)
print(f"t2: \n{t2}\n")

t3 = torch.stack([tensor, tensor], dim = 0)
t4 = torch.stack([tensor, tensor], dim = 1)

print(f"t3: \n{t3}\n")
print(f"t4: \n{t4}\n")

print(f"shape of t1: {t1.shape}\n")
print(f"shape of t2: {t2.shape}\n")
print(f"shape of t3: {t3.shape}\n")
print(f"shape of t4: {t4.shape}\n")

t1: 
tensor([[0.4130, 0.6300, 0.6954, 0.0936, 0.4130, 0.6300, 0.6954, 0.0936],
        [0.0321, 0.0377, 0.7239, 0.4694, 0.0321, 0.0377, 0.7239, 0.4694],
        [0.6381, 0.6953, 0.6005, 0.9967, 0.6381, 0.6953, 0.6005, 0.9967],
        [0.7694, 0.1750, 0.9768, 0.4009, 0.7694, 0.1750, 0.9768, 0.4009]])

t2: 
tensor([[0.4130, 0.6300, 0.6954, 0.0936],
        [0.0321, 0.0377, 0.7239, 0.4694],
        [0.6381, 0.6953, 0.6005, 0.9967],
        [0.7694, 0.1750, 0.9768, 0.4009],
        [0.4130, 0.6300, 0.6954, 0.0936],
        [0.0321, 0.0377, 0.7239, 0.4694],
        [0.6381, 0.6953, 0.6005, 0.9967],
        [0.7694, 0.1750, 0.9768, 0.4009]])

t3: 
tensor([[[0.4130, 0.6300, 0.6954, 0.0936],
         [0.0321, 0.0377, 0.7239, 0.4694],
         [0.6381, 0.6953, 0.6005, 0.9967],
         [0.7694, 0.1750, 0.9768, 0.4009]],

        [[0.4130, 0.6300, 0.6954, 0.0936],
         [0.0321, 0.0377, 0.7239, 0.4694],
         [0.6381, 0.6953, 0.6005, 0.9967],
         [0.7694, 0.1750, 0.9768, 0.4009]]])



In [ ]:
#Arithmetic operations

'''
  Matrix multiplication
'''
y1 = tensor @ tensor.T

y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

print(f"y1: \n{y1}\n")
print(f"y2: \n{y2}\n")
print(f"y3: \n{y3}\n")


y1: 
tensor([[1.0598, 0.5843, 1.2124, 1.1448],
        [0.5843, 0.7468, 0.9492, 0.9265],
        [1.2124, 0.9492, 2.2445, 1.5987],
        [1.1448, 0.9265, 1.5987, 1.7374]])

y2: 
tensor([[1.0598, 0.5843, 1.2124, 1.1448],
        [0.5843, 0.7468, 0.9492, 0.9265],
        [1.2124, 0.9492, 2.2445, 1.5987],
        [1.1448, 0.9265, 1.5987, 1.7374]])

y3: 
tensor([[1.0598, 0.5843, 1.2124, 1.1448],
        [0.5843, 0.7468, 0.9492, 0.9265],
        [1.2124, 0.9492, 2.2445, 1.5987],
        [1.1448, 0.9265, 1.5987, 1.7374]])



In [ ]:
tensor2 = 2 * torch.ones(3,3)
print(f"tensor2: \n{tensor2}\n")


y1 = tensor2 @ tensor2.T

y2 = tensor2.matmul(tensor2.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor2, tensor2.T, out = y3)

print(f"y1: \n{y1}\n")
print(f"y2: \n{y2}\n")
print(f"y3: \n{y3}\n")

tensor2: 
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

y1: 
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

y2: 
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

y3: 
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])



In [ ]:
'''
  Element wise multiplication
'''

z1 = tensor2 * tensor2

z2 = tensor2.mul(tensor2)

z3 = torch.rand_like(z1)
torch.mul(tensor2, tensor2, out = z3)

print(f"z1: \n{z1}\n")
print(f"z2: \n{z2}\n")
print(f"z3: \n{z3}\n")

z1: 
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

z2: 
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

z3: 
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])



In [ ]:
'''
  Single element tensor
'''

agg = tensor2.sum()

print(f"agg: {agg}")
print(f"agg type : {agg.dtype}")

'''
  item() will convert a single element tensor to a python
  numerical value
'''
agg_item = agg.item()
print(agg_item, type(agg_item))


agg: 18.0
agg type : torch.float32
18.0 <class 'float'>


In [3]:
# in place operations

#the methods are suffixed with _

tensor = torch.ones(3,3)

print(f"tensor: \n{tensor}\n")

#in place suffixed with _
tensor.add_(5)

print(f"tensor: \n{tensor}\n")

#not in place
tensor.add(5)

print(f"tensor: \n{tensor}\n")

'''
    In-place operations save some memory,
    but can be problematic when computing derivatives because of an
    immediate loss of history. Hence, their use is discouraged.
'''


tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor: 
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

tensor: 
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])



#Bridge with numpy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [7]:
# Tensor to numpy array

tensor = torch.ones(3,3)
print(f"tensor datatype: {tensor.dtype}")

np_array = tensor.numpy()
print(f"np_array datatype: {np_array.dtype}")

print(f"tensor: \n{tensor}\n")
print(f"numpy array: \n{np_array}\n")


#A change in the tensor reflects the change in numpy array

tensor.add_(2)

print(f"tensor: \n{tensor}\n")
print(f"numpy array: \n{np_array}\n")


tensor datatype: torch.float32
np_array datatype: float32
tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

numpy array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tensor: 
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

numpy array: 
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]



In [6]:
#Numpy array to tensor

np_array = np.ones((3,3))

tensor = torch.from_numpy(np_array)

print(f"Tensor: \n{tensor}\n")
print(f"Numpy array: \n{np_array}\n")
print(f"Tensor datatype: {tensor.dtype}")
print(f"Numpy array datatype: {np_array.dtype}")


#changes in the numpy array reflects in the tensor

np.add(np_array, 5, out=np_array)

print(f"Tensor: \n{tensor}\n")
print(f"Numpy array: \n{np_array}\n")



Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Numpy array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Tensor datatype: torch.float64
Numpy array datatype: float64
Tensor: 
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], dtype=torch.float64)

Numpy array: 
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]

